modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "integrated_server_watchdog"
version = "${version}"
displayName = "Integrated Server Watchdog"
authors = "KostromDan"
description = '''
Watchdog system for integrated Minecraft server
'''
#logoFile = ""

[[dependencies.integrated_server_watchdog]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.integrated_server_watchdog]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.integrated_server_watchdog]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
